--- 
- 
  become: true
  handlers: 
    - 
      name: "docker status"
      service: "name=docker state=started"
  hosts: docker
  tasks: 
    - 
      name: "Install Git"
      package: 
        name: git
        state: present
    - 
      apt: 
        update_cache: true
      name: "Run update"
    - 
      name: "Install JDK"
      package: 
        name: default-jdk
        state: present
    - 
      copy: 
        dest: /home/edureka/
        src: /home/edureka/chromedriver
      name: "Copy chromedriver"
    - 
      name: "Install chromium browser"
      package: 
        name: chromium-browser
        state: present
    - 
      name: "Install chromium driver"
      package: 
        name: chromium-chromedriver
        state: present
    - 
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: true
      name: "Install packages that allow apt to be used over HTTPS"
      vars: 
        packages: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
    - 
      apt_key: 
        state: present
        url: "https://download.docker.com/linux/ubuntu/gpg"
      name: "Add an apt signing key for Docker"
    - 
      apt_repository: 
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
        state: present
      name: "Add apt repository for stable version"
    - 
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: true
      name: "Install docker and its dependecies"
      notify: 
        - "docker status"
      vars: 
        packages: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - 
      command: "swapoff -a"
      name: "Disable swap"
      when: "ansible_swaptotal_mb > 0"
